### ISSUE TITLE
Add analysis and context for "Justified" usage of "!"

### ISSUE THREAD

**Issue by ironcev** [tom-englert/Nullable.Extended#10]
Null-forgiving operator can be misused or used without much thinking, just to silence the compiler. Therefore, in our team we have addopted the following guideline:

*Every usage of "!" must be documented in a comment that is placed above the code line and starts with "!". E.g:*

    // ! someObject is not null because of this and that.
    someObject!.DoSomething();

    // ! This needs a bit of a more explanation so the
    // ! explanation goes through several rows and every
    // ! row starts with "!".
    someOtherObject!.DoSomethingElse();

In other words, every usage of "!" must be "justified".

Would it make sense to add such check to Nullable.Extended and to have additional Context named e.g. "Justified" or "Explained" or similar?

The term "Justify" and the proposal to use comments directly above that start with "!" is just a first idea. I can also imagine something more ReSharper like:

    // Nullable.Extended disable: Here comes the explanation.

But I like "!" as distinguisher because it is simple to write, does not introduce heavy clutter, and has a clear visual and mental association to the null-forgiving operator.

**Comment by tom-englert** [comment]
I also like the "// !" notation, it's so much easier to type, it's even usable without a special code fix analyzer. 👍

**Comment by ironcev** [comment]
Perfekt, let's then go with "// !" :-) To the implementation, we also wanted to have a Roslyn analyzer as well, that will warn us (or even more importantly break a build if Warnings as errors option is set) if a justification comment is not available, regardles of the Nullable.Extended being provided. We've actually planned to develop this analyzer on our own.

Do you see a potential synergy here? E.g. developing the analzyer within Nullable.Extended and using it in the VS extension but making it also available as a NuGet package? Or you see it as an overhead? We could also potentially contribute to the development of the analyzer.

**Comment by tom-englert** [comment]
There is already an analyzer project here: 
https://github.com/tom-englert/Nullable.Extended/tree/master/src/Nullable.Extended.Analyzer

This is the diagnostic analyzer I had started with before I have moved this part to the VSIX; with this new use case in mind we can simply reactivate it and add the new functionality:
https://github.com/tom-englert/Nullable.Extended/blob/0c0dc08a5c75ff6c2053776ce5855c35eaaf1227/src/Nullable.Extended.Analyzer/Nullable.Extended.Analyzer/NullForgivingDetectionAnalyzer.cs

We can then add a shared project where the code used by both projects will go to.

**Comment by tom-englert** [comment]
@ironcev can you try v1.10 (https://www.nuget.org/packages/Nullable.Extended.Analyzer/)?

**Comment by ironcev** [comment]
Thanks for implementing this so quickly!! Actually I wanted to jump in and contribute, but wasn't nearly up to your speed :-) I'll try it out and let you know.

**Comment by tom-englert** [comment]
@ironcev finally got some time to update the readme to reflect the new feature.
Could you try the analyzer yet?
