### ISSUE TITLE
Not working for `dotnet build`

### ISSUE THREAD

**Issue by kjpgit** [tom-englert/Nullable.Extended#11]
Am I doing something wrong here, is there required configuration?  I'm on Linux.

```
$ dotnet --version  
6.0.201
dotnet new console
dotnet add package Nullable.Extended.Analyzer --version 1.10.4539
dotnet run
```

```
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
string envstring = Environment.GetEnvironmentVariable("DOESNOTEXIST")!;
Console.WriteLine("This is null: {0}", envstring);
```

Does not trigger any warnings.  

Tried adding this but the file is not being created
```
   <NullableExtendedAnalyzer>
          <LogFile>/tmp/foo.log</LogFile>
      </NullableExtendedAnalyzer>
```

**Comment by tom-englert** [comment]
I'm only using this with MSBuild on Windows.
If the analyzer is not invoked in your scenario, that's rather an issue with dotnet, not the analyzer.

**Comment by kjpgit** [comment]
Thanks.  I can find absolutely zero documentation about using analyzers with dotnet build, but I will keep looking and update this ticket if I get it working.  

By the way, thank you for this awesome project, I hope I get it working.  We heavily discourage `obj!` and use `__unwrap(obj)` instead:

```
public class correctness_is_always_job_one
{
    public static T __unwrap<T>(T? obj) {
        if (obj is null) {
            throw new ArgumentNullException();
        }
        return obj;
    }
}
```

The new dotnet 6.0 "implicit global usings" makes it zero friction for all source code to access __unwrap:
```
  <ItemGroup>
      <Using Include="CPCommon.correctness_is_always_job_one" Static="True" />
  </ItemGroup>
