### ISSUE TITLE
Nullable<T>.GetValueOrDefault same as null forgiving operator

### ISSUE THREAD

**Issue by flexxxxer** [tom-englert/Nullable.Extended#12]
The [null forgiving operator does not work for `Nullable<T>` types](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDKgZgASy3A7Mgb2QEgBiAOwFcAbagQwCNqBTDZ8xlk9DAZwBcATpQDG/DAAVmg3gHtyGIkmLEeUOAAYMHALbMA3CQC+JbnABsk6XPIB+DAHFm/KTPkAKBrNnUMAT2ZeAEpFEmJXGwxBZwwAXm1mAHcrN3J3IMNlYmj+ADpdVniAIhFZUTKizJUASwAzdwDgrFwo5yriZmpeVigWqloqk2VuGBgSJRUI+XsAB2t5OMdnKbShSmYMsPUATncigpAMIowwDDnUgEJ8uj1N5SGjIA==), and [`Nullable<T>.GetValueOrDefault`](https://docs.microsoft.com/en-us/dotnet/api/system.nullable-1.getvalueordefault?view=net-6.0) is suggested to ignore the null case with `Nullable<T>`. I suggest introducing the same tracking and suppression mechanisms for `Nullable<T>.GetValueOrDefault` as introduced for the **null forgiving operator "!"**.

**Comment by tom-englert** [comment]
That would be a C# feature, it's not related to this project
