### ISSUE TITLE
Is there a way to analyze the unnecessary ?. in code

### ISSUE THREAD

**Issue by luizfbicalho** [tom-englert/Nullable.Extended#15]
Imagine this class

```C#

public class Base
{
     public Child Child {get;set;} = new Child();
}
public class Child
{
     public string Description {get;set;} = string.Empty;
}


```

and in my code I have 

```C#
var x = new Base();

var d = x.Child?.Description;
```

How can I show a message that this ?. is not necessary because it can't be null?

**Comment by tom-englert** [comment]
I always had this message, however it seems to be a feature of ReSharper, not Roslyn.

To have this without R# you could write an analyzer for conditional access qualifier expressions, that checks nullability of the left expression.

Or raise a feature request at https://github.com/dotnet/roslyn

**Comment by tom-englert** [comment]
Why not, happy to accept a PR for this

**Comment by luizfbicalho** [comment]
I'll try to understand your code first to try that

**Comment by tom-englert** [comment]
I think it's https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1508 what you are looking for.
You just have to enable all rules.
