### ISSUE TITLE
Can it report usage of "!" as compiler error instead of editor warning?

### ISSUE THREAD

**Issue by klesun** [tom-englert/Nullable.Extended#16]
Hi. I installed the [NuGet package](https://www.nuget.org/packages/Nullable.Extended.Analyzer/), but my project still builds without warnings even though there actually are unjustified usages of the null-forgiving operator. My IDE (Rider) does not show any warnings either.

To enforce the checks regardless of specific team member's environment, is there a way to make them a part of project build process rather than just editor configuration?

Thanks in advance.

**Comment by tom-englert** [comment]
Sure, you can set the severity like for any other analyzer:

![image](https://github.com/user-attachments/assets/d2f61b5b-ad96-4561-9330-c6869771a313)

**Comment by klesun** [comment]
Sorry, my question was not about changing severity, it was about making this validation a part of solution compilation process so that it could be used without IDE. Maybe I'm doing something wrong and missing something obvious, but after I installed this NuGet, nothing really happened, the project still kept compiling without warning. Could it be that there are some extra steps needed after installing the NuGet to make it a part of my code compilation, like maybe adding a reference to it in .csproj?

**Comment by klesun** [comment]
Related I guess: https://github.com/dotnet/roslyn/issues/33558

**Comment by tom-englert** [comment]
No, there is no additional step needed.
Adding the package should be enough.

Maybe try to change the severity to error (see e.g. #11)

**Comment by klesun** [comment]
Oh, I think I figured it out. It seems that it did not work because I was trying to use it in an ASP.NET 4.8 project that defined NuGet installations through packages.config.
```xml
<package id="Nullable.Extended.Analyzer" version="1.15.6169" targetFramework="net48" developmentDependency="true" />
```
When I tried it in a newer version of that project, that uses NET Core 8 and NuGets are installed in the .csproj:
```xml
<PackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6169">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```
Then warnings finally started showing!
![image](https://github.com/user-attachments/assets/e69fa5b7-dcc2-4893-bc06-4e5f4795d69e)

Thank you very much for this awesome plugin!

I also share @kjpgit's hate for the usage of `obj!` instead of the null-safe runtime assertions, though my unwrapping helper function works through a null-coalese operator:
```cs
string? somethingMaybe = GetSomethingIfAny();
string something = somethingMaybe ?? Null.Never();
...
public static class Null
{
    /**
     * you can use this for safe runtime null checks instead of the unsafe null-forgiving "!" operator:
     * string? nullable = getSomething();
     * string unsafeAssertion = nullable!;
     * string safeAssertion = nullable ?? Null.Never();
     */
    public static dynamic Never(string? message = null)
    {
        throw new ArgumentNullException(message);
    }
}
```
