### ISSUE TITLE
Please add an icon to the tool window

### ISSUE THREAD

**Issue by ChrisTorng** [tom-englert/Nullable.Extended#5]
I'm using [Visual Studio Iconizer](https://marketplace.visualstudio.com/items?itemName=OlegTarasov.VisualStudioIconizerforVisualStudio15). Nullable.Extended tool window shows as text, no icon. Visual Studio Iconizer says:

> All tool window tabs that have a hidden icon are converted into tabs that have an icon and don't have text title. Tabs that don't have icons, retain their text.

Please add an icon to the tool window for Visual Studio Iconizer to show it, thank you.

**Comment by tom-englert** [comment]
There's no documentation where to add the icon. 
Maybe you can provide a PR with the required changes?

**Comment by ChrisTorng** [comment]
I have add an [issue](https://github.com/olegtarasov/VSIconizer/issues/6) for a guide of VSIconizer. From a [comment](https://devblogs.microsoft.com/visualstudio/a-more-integrated-terminal-experience/#comment-24189), it says:

> The extension works by using the [ToolWindowPane.BitmapResourceID](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.toolwindowpane.bitmapresourceid?view=visualstudiosdk-2019) to display the image.

And I have no experience on how to develop an extension. Sorry for not able to provide a PR.

**Comment by tom-englert** [comment]
@ChrisTorng OK, with that info it was quite easy.

**Comment by lennartb-** [comment]
I was just about to check whether there's an issue about that here. Nice to see that my original comment helped some more people 😄
