### ISSUE TITLE
The tool window cannot be used by keyboard, it demands using the mouse

### ISSUE THREAD

**Issue by ironcev** [tom-englert/Nullable.Extended#8]
Thanks for this awesome VS extension! It proves to be very useful in code reviews, catching of design and code smells and makes discussing the topic of null-forgiving operator (mis)use much easier!

At the moment, the only way to use the tool window is via mouse. E.g. when the tool window is open, the focus is on the Refresh button and solely by using the keyboard e.g. Tab it is not possible (or at least I didn't manage it) to reach the grid. Also, once in the grid, it is not possible to use e.g. Space or Enter to jump to the place in code. One must use mouse doubleclick.

For keyboard savy users this is a break in the workflow.

If possible, I would propose the following:

- Enable moving over the controls in toolbar and the grid via Tab key.
- Pressing Space or Enter in the grid navigates to the place in code.

**Comment by tom-englert** [comment]
Good point 👍

**Comment by ironcev** [comment]
Thanks for the quick implementation! Looking forward to having it published on Marketplace in v1.7 :-)

**Comment by tom-englert** [comment]
There are still some improvements in progress until the next release, but you can already use the CI-Build from here: https://www.vsixgallery.com/extension/Nullable.Extended.75a92614-c590-4401-b04b-04926c0e21cf
